### ISSUE TITLE
Percent online widget color

### ISSUE THREAD

**Issue by jcushman** [berkmancenter/internet_dashboard#2]
I think the percent online widget would look nicer with a more saturated color. Would you mind if I submitted a pull request?

**Comment by jdcc** [comment]
Sounds good! That color is lousy. Go for it.

**Comment by jcushman** [comment]
Great! Just change line 20 to be: "rgb(186, 89, 100);"

**Comment by jdcc** [comment]
NO. You do it. That's dumb.
